### ISSUE TITLE
Alterar adaptador

### ISSUE THREAD

**Issue by phgeek** [Infanatica/InfanaticaCepModule#1]
Como faço para utilizar outro adaptador?
E como posso defini-lo como padrão?

**Comment by diogomascarenha** [comment]
Bom dia Phillippe Caetano,

Para alterar o adaptador, você precisa criar um aquivo de configuração no "config/autoload/" com as configurações do adaptador que você deseja.

Um exemplo pode ser encontrado em "https://github.com/Infanatica/InfanaticaCepModule/blob/master/config/infanatica-cep-module.config.global.php.dist", no caso você precisa colocar esse arquivo na sua pasta "config/autoload/" sem o ".dist", exemplo "config/autoload/infanatica-cep-module.config.global.php".

A configuração padrão está para o "ViaCepAdapter", mas você pode escolher qualquer um dos Adapters.
Atualmente temos os Adapters abaixo.

InfanaticaCepModule\Service\ViaCepAdapter
InfanaticaCepModule\Service\PostmonAdapter
InfanaticaCepModule\Service\CorreioControlAdapter
InfanaticaCepModule\Service\RepublicaVirtualAdapter

Modifique o alias no arquivo "config/autoload/infanatica-cep-module.config.global.php" para definir o Adapter.

Exemplo: 
Se você quiser utilizar o Adapter "CorreioControlAdapter", você precisará alterar o arquivo "config/autoload/infanatica-cep-module.config.global.php" para o conteúdo abaixo. 

``` php
<?php

return array(
    'service_manager' => array(
        'aliases' => array(
            'InfanaticaCepModule\Adapter\CepDefaultAdapter' => 'InfanaticaCepModule\Service\CorreioControlAdapter'
        ),
    ),
);
```

**Comment by phgeek** [comment]
Legal! Funcionou. :+1: 

Obrigado!

**Comment by sergiohermes** [comment]
Olá, Parabéns pelo módulo!

Se caso cair um serviço tem como ele tentar buscar de um outro?

Abraço,

**Comment by phgeek** [comment]
:+1: isso seria bom Sergio.

**Comment by munizeverton** [comment]
É uma boa feature, mas por enquanto você pode implementar isso na sua aplicação.
Caso o response não seja um endereço válido você troca o adapter.
